### ISSUE TITLE
Can not connect to www.pleer.com

### ISSUE THREAD

**Issue by zt1906** [sacert/SoundSea#18]
Please update your music website, it doesn't work at all in current version

**Comment by spectral369** [comment]
I've create a pull request. 
Everything is working again.(Hope so) With a new server instead of Pleer. #19

**Comment by ghost** [comment]
Website is not working again, unfortunately :(

**Comment by spectral369** [comment]
@glBeatriz Website is working again and I've fixed 'error 502' on my 'forked' version

**Comment by ghost** [comment]
thanks @spectral369!
I still get the message website not found though ("server IP address could not be found."). I tried on several browsers on computer and mobile phone. 
Is this the normal behaviour? or does the API in the application still work regardless of this browser error?

**Comment by spectral369** [comment]
Let's just be clear:
1 - I'm talking about my forked version (i.e https://github.com/spectral369/SoundSea)
Note: my pull request from few months back was not merged with this version #19 
2 -  Website is https://datmusic.xyz (pleer.com is not available anymore)
3 -  API  - https://github.com/alashow/datmusic-api
4 - Proof ![alt tag](https://media.giphy.com/media/POIzAVRxONLLRFs1JB/giphy-downsized-large.gif)

**Comment by ghost** [comment]
clear!
Will give it a try!
